web/routes/auth.py
import functools

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from web.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        validcode = request.form['validcode']

        db = get_db()
        error = None
        if validcode != 'Jinhetech1@#':
            error = 'Validation code is not correct!'
        elif not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif db.execute('SELECT id FROM user WHERE username = ?',
                        (username, )).fetchone() is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            db.execute('INSERT INTO user (username, password) VALUES (?, ?)',
                       (username, generate_password_hash(password)))
            db.commit()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.j2')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute('SELECT * FROM user WHERE username = ?',
                          (username, )).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('stocking.index'))

        flash(error)

    return render_template('auth/login.j2')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute('SELECT * FROM user WHERE id = ?',
                                  (user_id, )).fetchone()


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('stocking.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

web/templates/base.j2
<!doctype html>
<title>{% block title %}{% endblock %} - ASTERIA</title>
<link rel="stylesheet"
    href="{{ url_for('static', filename='style.css') }}?_={{timestamp()}}">
<script
    src="https://cdn.bootcss.com/echarts/4.4.0-rc.1/echarts.min.js"></script>
<nav>
    <h1>ASTERIA</h1>
    {% set cate = cates() %}
    <ul class="cates">
        <li><a href="{{ '#' if cate == 'stocking' else '/stocking' }}"
                class="{{ 'active' if cate == 'stocking' else '' }}">STOCKING</a>
        </li>
        <li><a href="{{ '#' if cate == 'about' else '/about' }}"
                class="{{ 'active' if cate == 'about' else '' }}">ABOUT</a>
        </li>
    </ul>
    <ul class="guides">
        {% if g.user %}
        <li><span>{{ g.user['username'] }}</span></li>
        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        {% else %}
        <li><a href="{{ url_for('auth.register') }}">Register</a></li>
        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
        {% endif %}
    </ul>
</nav>
<section class="content">
    <header>
        {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
</section>
<script type="text/javascript">
    console.log('')
</script>